/// All 23 permits for the CHN1A data-center project, with phase, lead time, cost, risk and status.
table Permits
	lineageTag: 62f320bf-97cd-4c7b-80a6-69ffdc4addce

	/// Total number of permits in the current filter context.
	measure 'Permit Count' = COUNTROWS ( Permits )
		formatString: #,##0
		lineageTag: 3c3e2c3f-5c17-4d47-9a6b-54d50ae6ef3c

	/// Permits with status Completed.
	measure Completed = CALCULATE ( [Permit Count], Permits[Status] = "Completed" )
		formatString: #,##0
		lineageTag: e67ff156-0653-4fbb-978e-f46d3194a34f

	/// Permits currently In Progress.
	measure 'In Progress' = CALCULATE ( [Permit Count], Permits[Status] = "In Progress" )
		formatString: #,##0
		lineageTag: d6403d9e-c8e4-422b-91c8-452142303783

	/// Permits not yet started.
	measure Pending = CALCULATE ( [Permit Count], Permits[Status] = "Pending" )
		formatString: #,##0
		lineageTag: 85750228-a545-4a5c-b7c3-2b49afe9fee8

	/// Sum of lead-time days across permits.
	measure 'Total Lead Days' = SUM ( Permits[LeadDays] )
		formatString: #,##0
		lineageTag: cd6de874-0012-45ee-bc0d-bf0abc590de6

	/// Sum of estimated permit cost (THB).
	measure 'Total Budget' = SUM ( Permits[Cost] )
		formatString: #,##0
		lineageTag: a2b0b9c2-eb06-4aea-af34-4e3458cd692b

	/// Share of permits completed.
	measure '% Complete' = DIVIDE ( [Completed], [Permit Count] )
		formatString: 0%
		lineageTag: 35a8a7fb-4058-400f-9688-4a27dfcf2bba

	/// Gantt offset: project month each permit starts (transparent segment).
	measure 'Start (month)' = SUM ( Permits[StartMonth] )
		formatString: 0.0
		lineageTag: 042b194d-99ff-48f6-bf22-be5825b4d92a

	/// Gantt bar length in months.
	measure 'Duration (months)' = SUM ( Permits[DurationMonths] )
		formatString: 0.0
		lineageTag: 29bf8c5a-71a1-4ff8-99bb-d7b855837d8c

	column ID
		dataType: int64
		isKey
		lineageTag: d76fd3b1-a5fe-455b-8e33-f9a344c21e66
		summarizeBy: none
		sourceColumn: ID

	column Permit
		dataType: string
		lineageTag: d20bc97d-cae3-486d-893c-fc46e88a81d0
		summarizeBy: none
		sourceColumn: Permit

	column Authority
		dataType: string
		lineageTag: 322b0b31-77a1-4d40-9198-d9e085812867
		summarizeBy: none
		sourceColumn: Authority

	column Phase
		dataType: string
		lineageTag: 1f3717b3-8d9a-4b4a-87fd-f251aa561977
		summarizeBy: none
		sourceColumn: Phase
		sortByColumn: PhaseNo

	column PhaseNo
		dataType: int64
		isHidden
		lineageTag: 5a4465f2-0517-4058-8a9a-c2b14e5d8bfb
		summarizeBy: none
		sourceColumn: PhaseNo

	column LeadDays
		dataType: int64
		lineageTag: de64054a-4bf9-4bab-bad8-cf58089027ff
		summarizeBy: sum
		sourceColumn: LeadDays

	column Cost
		dataType: int64
		formatString: #,##0
		lineageTag: fef53e60-27b3-417c-aa0f-7f84bd50a93c
		summarizeBy: sum
		sourceColumn: Cost

	column Risk
		dataType: string
		lineageTag: bfe498ea-b53d-49fc-bcb9-992fda0cf95c
		summarizeBy: none
		sourceColumn: Risk

	column Status
		dataType: string
		lineageTag: 58a179dc-e278-4427-b1ee-e6978ba6e3e0
		summarizeBy: none
		sourceColumn: Status

	column StartMonth
		dataType: double
		isHidden
		lineageTag: d8d3106a-60df-4e47-9402-9edf8e842639
		summarizeBy: none
		sourceColumn: StartMonth

	column DurationMonths
		dataType: double
		lineageTag: 3d6adf1a-2958-4468-9728-fd56bfed6e45
		summarizeBy: sum
		sourceColumn: DurationMonths

	partition Permits = calculated
		mode: import
		source =
				DATATABLE (
					"ID", INTEGER,
					"Permit", STRING,
					"Authority", STRING,
					"Phase", STRING,
					"PhaseNo", INTEGER,
					"LeadDays", INTEGER,
					"Cost", INTEGER,
					"Risk", STRING,
					"Status", STRING,
					"StartMonth", DOUBLE,
					"DurationMonths", DOUBLE,
					{
					{ 1, "Company Registration", "DBD", "1. Development", 1, 30, 5000, "Low", "Completed", 0.0, 1.0 },
					{ 2, "BOI Promotion Certificate", "BOI", "1. Development", 1, 120, 0, "Critical", "Completed", 0.5, 4.0 },
					{ 3, "Foreign Business License", "DBD", "1. Development", 1, 60, 10000, "Low", "Completed", 0.5, 2.0 },
					{ 4, "Land Use & Zoning", "DPW", "1. Development", 1, 30, 2000, "Low", "Completed", 0.0, 1.0 },
					{ 5, "Environmental Impact Assessment", "ONEP", "1. Development", 1, 180, 350000, "Critical", "Completed", 0.5, 6.0 },
					{ 6, "Building Construction Permit", "DPW", "2. Design & Planning", 2, 60, 15000, "Critical", "Completed", 6.0, 2.0 },
					{ 7, "Road Access / Highway", "DPW", "2. Design & Planning", 2, 45, 8000, "High", "In Progress", 6.0, 1.5 },
					{ 8, "Grid Connection Approval", "PEA/MEA", "2. Design & Planning", 2, 60, 75000, "High", "Completed", 2.0, 2.0 },
					{ 9, "Power Availability (ERC)", "ERC", "2. Design & Planning", 2, 30, 0, "Critical", "Completed", 0.5, 1.0 },
					{ 10, "HV Substation Approval", "PEA/MEA", "2. Design & Planning", 2, 90, 150000, "High", "Completed", 6.0, 3.0 },
					{ 11, "Water Supply Connection", "MWA/PWA", "3. Construction", 3, 45, 30000, "Low", "Completed", 8.0, 1.5 },
					{ 12, "Wastewater / Drainage", "MWA", "3. Construction", 3, 45, 37500, "Low", "Completed", 8.0, 1.5 },
					{ 13, "Fire Protection System", "DPW", "3. Construction", 3, 30, 115000, "High", "Completed", 8.0, 1.0 },
					{ 14, "Generator & Fuel Storage", "DOEB", "3. Construction", 3, 60, 15000, "High", "In Progress", 8.0, 2.0 },
					{ 15, "Telecom / Fiber", "NBTC", "3. Construction", 3, 45, 10000, "Low", "In Progress", 8.0, 1.5 },
					{ 16, "Electrical Inspection", "PEA/MEA", "3. Construction", 3, 14, 5000, "Low", "In Progress", 10.0, 0.5 },
					{ 17, "Fire Safety Inspection", "Fire Authority", "4. Commissioning", 4, 7, 0, "Low", "In Progress", 11.0, 0.4 },
					{ 18, "Building Completion", "DPW", "4. Commissioning", 4, 7, 3000, "Low", "In Progress", 11.0, 0.4 },
					{ 19, "Occupancy Certificate", "DPW", "4. Commissioning", 4, 14, 2000, "High", "In Progress", 11.3, 0.6 },
					{ 20, "Commissioning & Utility Acceptance", "Utilities", "4. Commissioning", 4, 21, 22500, "Low", "Pending", 11.5, 0.8 },
					{ 21, "Factory License", "DIW", "5. Operations", 5, 30, 5000, "Low", "Pending", 12.0, 1.0 },
					{ 22, "PDPA Compliance", "PDPC", "5. Operations", 5, 30, 0, "Low", "Pending", 12.0, 1.0 },
					{ 23, "Cybersecurity Compliance", "NCSA", "5. Operations", 5, 30, 0, "Low", "Pending", 12.0, 1.0 }
					}
				)

	annotation PBI_ResultType = Table
